### ISSUE TITLE
isCName设置为true后上传错误

### ISSUE THREAD

**Issue by zhongjq** [iiDestiny/laravel-filesystem-oss#11]
你好，你的包也存在使用自定义域名的bug，能修复不
[支持 getUrl 方法，解决阿里云 isCName 和 CDN 冲突的问题](https://github.com/xxtime/flysystem-aliyun-oss/issues/1)

**Comment by williamqian** [comment]
同问

**Comment by iiDestiny** [comment]
@williamqian @zhongjq 都是测试过的呢，你们是不是配置哪里写错了。

![image](https://user-images.githubusercontent.com/17637481/66891542-08dd9280-f01c-11e9-9732-dfdcf8b9d0b6.png)

![image](https://user-images.githubusercontent.com/17637481/66891619-3cb8b800-f01c-11e9-9b72-6afbbc685647.png)

![image](https://user-images.githubusercontent.com/17637481/66891640-47734d00-f01c-11e9-85df-d99dd969109a.png)

**但是有个前提你必须在后台自己绑定好自定义域名，并且能成功访问**

![image](https://user-images.githubusercontent.com/17637481/66891695-64a81b80-f01c-11e9-87ed-a9b919063ac5.png)

![image](https://user-images.githubusercontent.com/17637481/66891725-74276480-f01c-11e9-8e3f-2dd2ca81e516.png)

![image](https://user-images.githubusercontent.com/17637481/66891757-83a6ad80-f01c-11e9-9f02-6e282d6c2fea.png)

因为太忙了，所以没有及时回复抱歉，希望能帮到你们

**Comment by iiDestiny** [comment]
## 补充

![image](https://user-images.githubusercontent.com/17637481/66891984-06c80380-f01d-11e9-9ed5-9d3c50891df3.png)

![image](https://user-images.githubusercontent.com/17637481/66892000-10516b80-f01d-11e9-9282-fc30b0dadad6.png)

**Comment by iiDestiny** [comment]
![image](https://user-images.githubusercontent.com/17637481/66892030-29f2b300-f01d-11e9-92a3-60b55a5129bf.png)
