### ISSUE TITLE
root 设置了没有效果

### ISSUE THREAD

**Issue by wl496928838** [iiDestiny/laravel-filesystem-oss#12]
root 设置了没有效果

**Comment by iiDestiny** [comment]
这里应该是前缀文档有问题

**Comment by woodongwong** [comment]
root 不好使， 不知道大佬怎么设置的，是否可以给个示例？ 目前我的bucket 是 sge-pjs, 不论root设置成什么都不行， 比如： /uploads 、 uploads 、 uploads/ 、 /sge-pjs/uploads/  .......
