### ISSUE TITLE
自定义域名开启cdn存在问题

### ISSUE THREAD

**Issue by inbjo** [iiDestiny/laravel-filesystem-oss#13]
自定义域名开启cdn之后会导致`put`,`delete`等api失败。  
原因是开启cdn之后解析的别名地址和不开启解析的别名地址是不一致的。  
不开启  
```
xxx.oss-cn-shenzhen.aliyuncs.com
```
开启  
```
xxx.com.w.kunlunca.com
```
我的使用场景是后端签名前端直传至oss,使用了自定义域名并开启了cdn。直传使用自定义域名不受开不开启cdn影响。  
建议增加一个选项，将直传域名和ENDPOINT区别开来。

**Comment by iyueshang** [comment]
同意，我也遇到了这个问题

**Comment by Yooole** [comment]
同样遇到这个问题 

临时解决方案 
在上传的地方修改配置项
config(['filesystems.disks.oss.endpoint' => 'oss-cn-beijing.aliyuncs.com']);

**Comment by Yooole** [comment]
临时解决方案 config(['filesystems.disks.oss.endpoint' => 'oss-cn-beijing.aliyuncs.com']);

**Comment by iiDestiny** [comment]
今天处理和发布新功能。

**Comment by iiDestiny** [comment]
看了一下，这貌似是 PHP 官方 SDK 的 bug，我已经给他们提出 issue 了，你们上传时先不要用 cdn 加速。
可以模仿 @Yooole  的临时解决方案，官方有更新我第一时间改动

**Comment by iyueshang** [comment]
好的  感谢

**Comment by iiDestiny** [comment]
近期发布了 2.0 版本，欢迎继续使用

发行说明：https://github.com/iiDestiny/laravel-filesystem-oss/releases/tag/2.0

**Comment by iiDestiny** [comment]
CDN 加速的域名有几个接口访问非常慢，还有几个接口会直接报错如「检查文件是否存在」
咨询了一下官方技术客服，反馈是不推荐使用 CDN 域名访问上传接口。

下个版本打算设置一个「上传  endpoint」和一个「显示 URl 用的 endpoint」

**Comment by raychuang** [comment]
应该增加 cdnDomain配置，分离上传域名与显示域名。
OssAdapter 中 normalizeHost中让  cdnDomain优先级最高。
这样配置中endpoint配置还能继续使用oss域，而getUrl也能正常的获取cdn链接

**Comment by iiDestiny** [comment]
@raychuang 等这段时间忙完就开始弄。

**Comment by Louhwz** [comment]
还有一种可能是文件写入时权限不足，导致上传文件为空，亲测修改目录权限即可。

**Comment by iiDestiny** [comment]
@Louhwz OSS 文件读写权限吗？

**Comment by Louhwz** [comment]
> @Louhwz OSS 文件读写权限吗？

是的。我的场景是用户上传头像文件等缓存目录，之后再从缓存目录上传到oss，这个过程中发现由于缓存目录的读写权限会出现问题，添加权限以后就解决了。

**Comment by iiDestiny** [comment]
一般有很多使用者为了安全考虑是设置私有，所以这块之后还得改改。

**Comment by keke996** [comment]
现在最新版本还是不能兼容cdn吗？

**Comment by jasonencode** [comment]
提提速吧，要不然只能fork新版本出去了

**Comment by seth-shi** [comment]
临时解决方法:
```
Storage::disk('oss')->getAdapter()->setCdnUrl('cdn域名')
```

作者可以考虑直接`OssStorageServiceProvider`增加以下配置
`$adapter->setCdnUrl($config['xxx'])`

**Comment by iiDestiny** [comment]
我试了下， cdn 可以上传了，操作流程如下

![image](https://user-images.githubusercontent.com/17637481/163953848-63dd7390-0745-42c8-a066-bca5c9221ac1.png)

![image](https://user-images.githubusercontent.com/17637481/163953856-3f69adb5-90a7-4112-97c8-ae8652413fcd.png)

![image](https://user-images.githubusercontent.com/17637481/163953867-e7af0a1d-0126-46d1-b772-2ebe192d5558.png)

![image](https://user-images.githubusercontent.com/17637481/163953877-7da3126c-58c9-4b7f-8899-7e40ead89061.png)

![image](https://user-images.githubusercontent.com/17637481/163953887-14366d25-578a-4925-999f-b9768e69436a.png)
