### ISSUE TITLE
packagist.org上的版本没有同步

### ISSUE THREAD

**Issue by iwisen** [iiDestiny/laravel-filesystem-oss#16]
packagist.org此包的版本还停留在1.2.1，麻烦大佬看看是否自动更新出问题了

**Comment by iiDestiny** [comment]
稍等，我看看。

**Comment by iiDestiny** [comment]
![image](https://user-images.githubusercontent.com/17637481/74224593-1cf87e80-4cf4-11ea-8c90-0e54f100883c.png)

目前是自动更新的状态，可能需要等等。

**Comment by iwisen** [comment]
2天前的1.2.2也还没有同步呢，可能是出问题了

**Comment by iiDestiny** [comment]
好了，刚排查了一下发现是 composer.json 里面版本号约束写错了，以后可以运行检查一下

```
composer validate
```
