### ISSUE TITLE
上传图片设置content-type的问题

### ISSUE THREAD

**Issue by noobzhp** [iiDestiny/laravel-filesystem-oss#19]
用laravel的文件系统put方法，上传到阿里云oss以后访问图片是下载的形式，能再上传的时候设置content-type吗？在网上说设置这个能直接浏览器访问

**Comment by iiDestiny** [comment]
请确保上传正确的图片格式。

![image](https://user-images.githubusercontent.com/17637481/78102986-47c2a180-741e-11ea-97d3-651a0279221c.png)

![image](https://user-images.githubusercontent.com/17637481/78103017-59a44480-741e-11ea-8a20-0a3d82b38ef2.png)

![image](https://user-images.githubusercontent.com/17637481/78103077-835d6b80-741e-11ea-99c3-ecd93de78572.png)

![image](https://user-images.githubusercontent.com/17637481/78103085-87898900-741e-11ea-8a13-8d66a326a957.png)

**Comment by nihaozym** [comment]
<script>alert(1)<script>
