### ISSUE TITLE
验签最后一步未通过，求思路

### ISSUE THREAD

**Issue by Tamn9208** [iiDestiny/laravel-filesystem-oss#21]
// 验证签名
        $ok = openssl_verify($authStr, $authorization, $pubKey, OPENSSL_ALGO_MD5);
这里出现不ok，求楼主提供一个检测思路

**Comment by iiDestiny** [comment]
嗯？验签扩展包提供了方法，直接用不成功吗？

**Comment by Tamn9208** [comment]
对，就是拓展包这里最好一步没通过，因为这里没有任何提示，所以请教下

**Comment by iiDestiny** [comment]
1. 签名时设置回调地址
2. 回调的地址中处理完需要返回 json 数据，返回的数据就是前端 network 看到的数据

> 可以打 log 来查看是否正确进入回调

**Comment by Tamn9208** [comment]
验签是发生在回调中，回调没问题，返回json也跟问题没关系呢。。我说的是验签过程中
