### ISSUE TITLE
是否支持「OSS 传输加速」？

### ISSUE THREAD

**Issue by jxlwqq** [iiDestiny/laravel-filesystem-oss#22]
OSS 传输加速，是专为 OSS 的互联网上传与下载加速设计的服务。OSS 传输加速，利用全球分布的节点、调度策略与网络链路优化、协议栈参数智能调节、OSS 存储服务层配套优化，提供端到端的传输加速方案。支持上传加速、下载加速，且对静态文件、动态更新文件、非热点文件下载都可以支持加速，无需预热。同时，支持对跨省、跨洋上传、下载，进行加速。

https://help.aliyun.com/document_detail/131312.html?spm=5176.8466035.0.0.7cdd1450vU13KV

**Comment by iiDestiny** [comment]
支持，已经在用。把全球加速开启，然后填写对应的地址。

**Comment by jxlwqq** [comment]
好的 谢谢。
