### ISSUE TITLE
内网上传，外网访问，需要怎样设置呢？

### ISSUE THREAD

**Issue by datangkang123** [iiDestiny/laravel-filesystem-oss#29]
目前如果设置为内网，则上传的文件无法外网访问；如果设置为外网，上传速度慢

**Comment by dogeow** [comment]
VPC 走的是内网，比如 http://oss-cn-shanghai-internal.aliyuncs.com，外网能不能访问是通过权限设置的，公开读就可以访问。

**Comment by datangkang123** [comment]
> 权限是公开的，但在配置文件中填写了内网，保存到数据库的链接是内网的，我现在需要在保存前将其替换为外网链接，访问正常。如果可以在配置文件中上传和读取分开填写网址就更好了。

**Comment by iiDestiny** [comment]
`setCdnUrl` 方法试一下
