### ISSUE TITLE
前端直传回调报 405 错误, 求指点下

### ISSUE THREAD

**Issue by toplyb** [iiDestiny/laravel-filesystem-oss#34]
- 返回的签名函数如下
```php
public function getSignature()
{
    $disk = Storage::disk('oss');
    $baseUrl = $_SERVER["HTTP_HOST"];

    $config = $disk->signatureConfig($prefix = 'douyin/', $callBackUrl = $baseUrl . '/admin/aliyun/callback', $customData = [], $expire = 30);
    return $config;
}
```

- 回调函数的路由是:
`    Route::get('/admin/aliyun/callback', [AdminDouYinController::class, 'ossCallback']);`

- 回调函数如下:
```php
public function ossCallback()
{
    $disk = Storage::disk('oss');
    list($verify, $data) = $disk->verify();
    return response()->json($data);
}
```

**Comment by houguang** [comment]
同样的问题
![image](https://user-images.githubusercontent.com/1720347/127732407-15191590-cc23-43e7-8802-479be346b912.png)
回调返回如下
![image](https://user-images.githubusercontent.com/1720347/127732422-e3122acf-4500-43bc-9e44-deea4fa69610.png)
@iiDestiny

**Comment by iiDestiny** [comment]
先看下验签通不通过，然后返回的数据是验签里面的 `$data`
