### ISSUE TITLE
Laravel 调用方法->bucket('test')后无法调用其他方法

### ISSUE THREAD

**Issue by ouyuan2016** [iiDestiny/laravel-filesystem-oss#35]
代码如下:
`

        $disk = Storage::disk('oss')->bucket('test');
        dd($disk->put('test','1231415235422342352354'));

`
错误返回

**Call to undefined method Iidestiny\\Flysystem\\Oss\\OssAdapter::put()**

取消->bucket('test')后方法调用正常

PHP:7.4 
Laravel:8.12

**Comment by iiDestiny** [comment]
这个功能是其他贡献值开发的，如果有问题可以暂时不用这个。在自己代码层面切换 bucket
