### ISSUE TITLE
希望能添加上传后返回的是自己绑定的域名功能 现在是OSS的地址，有点怪怪的

### ISSUE THREAD

**Issue by fishbigbig** [iiDestiny/laravel-filesystem-oss#37]

**Comment by iiDestiny** [comment]
![image](https://user-images.githubusercontent.com/17637481/163951904-e5f00672-ad58-41d8-9f6e-4941c312106f.png)

把 isCname 设置 true，然后把自己的 endpoint 设置为 cdn 域名

**Comment by fishbigbig** [comment]
这是来自牙套之家自动回复邮件。
 
您好，您的邮件我已经收到。牙套之家，牙科医患交流平台， 树立牙科和牙医的品牌，构建和谐医患关系.鱼大吉 TEL：18928058211 网站：http://www.yataohome.com 微信：fishbigbig 微信公众号：牙套之家 新浪微博：牙套之家论坛
