### ISSUE TITLE
Configure directory used inside of the OSS bucket

### ISSUE THREAD

**Issue by abuhurairah-aar** [iiDestiny/laravel-filesystem-oss#39]
Hi, is it possible to specify the directory that would be used inside this package configuration?

For example in S3 package I could do it like this inside the root:-
`'s3' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION', 'us-east-1'),
            'bucket' => env('AWS_BUCKET'),
            'root' => env('AWS_ROOT'),
            'url' => env('AWS_URL'),
            'endpoint' => env('AWS_ENDPOINT'),
],`

Please advise, thanks.

**Comment by iiDestiny** [comment]
prefix ?

**Comment by iiDestiny** [comment]
![image](https://user-images.githubusercontent.com/17637481/164353819-642dfbb8-93e4-44bc-a6da-1203cc768df3.png)

**Comment by abuhurairah-aar** [comment]
oh my bad, haven't notice that. I'll close this ticket.
Thanks a lot!
