### ISSUE TITLE
Class 'Iidestiny\Flysystem\Oss\Plugins\SignatureConfig' not found

### ISSUE THREAD

**Issue by youwen21** [iiDestiny/laravel-filesystem-oss#4]
v1.2依赖flysystem-oss的版本不对， 缺少SignatureConfig

**Comment by iiDestiny** [comment]
![image](https://user-images.githubusercontent.com/17637481/56629992-34417f00-6682-11e9-855d-6ae36611b3a9.png)

可以卸载重新安装

要么单独升级一下依赖

```
composer update iidestiny/flysystem-oss
```

最新版 flysystem-oss 目前是 `1.3.2`，可能是之前安装了老版本的 flysystem-oss

**Comment by iiDestiny** [comment]
可以看看你 flysystem-oss 的版本吗？

**Comment by youwen21** [comment]
是的  我版本的问题  我卸载了v1.2    安装v1.1就可以的
下载来来的依赖包里没有SignatureConfig

**Comment by iiDestiny** [comment]
```
composer require iidestiny/laravel-filesystem-oss -vvv
```

直接安装最新版就行。

**Comment by youwen21** [comment]
感谢支持～，  目前v1.1能满足我的使用。

**Comment by iiDestiny** [comment]
不客气，这个包主要是个适配包，核心代码还是 `flysystem-oss` 里面，1.2 的版本新增了 `前端 web 直传`。以后用得上可以升级一下。
