### ISSUE TITLE
laravel 10 不能用啊

### ISSUE THREAD

**Issue by gaojishu** [iiDestiny/laravel-filesystem-oss#50]
laravel 10 不能用啊

**Comment by bolechen** [comment]
试试行了没？https://github.com/iiDestiny/laravel-filesystem-oss/pull/51

**Comment by gaojishu** [comment]
安装成功了。 $disk = Storage::disk('oss'); 调用提示错误 ： "message": "access key id is empty",
    "exception": "OSS\\Core\\OssException",
    "file": "/www/wwwroot/lv10/vendor/aliyuncs/oss-sdk-php/src/OSS/OssClient.php",
    "line": 136,

**Comment by gaojishu** [comment]
array:4 [ // vendor/aliyuncs/oss-sdk-php/src/OSS/OssClient.php:104
  0 => null
  1 => "LTACW"
  2 => "oss-cn-hancs.com"
  3 => false
]

**Comment by gaojishu** [comment]
好了，和另一个包冲突了
