### ISSUE TITLE
Class 'Iidestiny\Flysystem\Oss\Plugins\TemporaryUrl' not found

### ISSUE THREAD

**Issue by ycgambo** [iiDestiny/laravel-filesystem-oss#7]
项目composer还依赖1.0版本flysystem-oss，需要更新一下依赖

**Comment by iiDestiny** [comment]
^1.0 代表 >= 1.0.0 <= 1.9999.9999

先 remove 包，然后重新安装一下。

**Comment by iiDestiny** [comment]
是不是之前单独安装过 flysystem-oss 这个包呢？如果是都 remove 了，再安装 laravel-filesystem-oss

**Comment by ycgambo** [comment]
没有 第一次安装 我排查一下

**Comment by iiDestiny** [comment]
可以找一个空目录验证一下

```shell
composer require "iidestiny/laravel-filesystem-oss" -vvv
```

![image](https://user-images.githubusercontent.com/17637481/57191403-bde12e80-6f57-11e9-93de-ecb33b9d92e0.png)

**Comment by ycgambo** [comment]
composer默认下载的是1.3.2版本的flysystem-oss，发布中没有包含TemporaryUrl


  - Installing iidestiny/flysystem-oss (1.3.2): Reading /Users/ycgambo/.composer/cache/files/iidestiny/flysystem-oss/b13b5033e93866d43aa33bb4bc6d0e9265cb3e92.zip from cache
Loading from cache
 Extracting archiveExecuting command (CWD): unzip -qq  '/Users/ycgambo/Documents/github/A_yk/laravel-vue-templates/vendor/iidestiny/flysystem-oss/384942a547986fcd47fe00513ed1cab0' -d '/Users/ycgambo/Documents/github/A_yk/laravel-vue-templates/vendor/composer/df8d6b50'
    REASON: iidestiny/laravel-filesystem-oss 1.2.1 requires iidestiny/flysystem-oss ^1.0 -> satisfiable by iidestiny/flysystem-oss[1.0, 1.0.1, 1.1, 1.2, 1.3, 1.3.1, 1.3.2, 1.3.3].

**Comment by ycgambo** [comment]
Problem 1
    - The requested package iidestiny/flysystem-oss (locked at 1.3.2, required as ^1.3.3) is satisfiable by iidestiny/flysystem-oss[1.3.2] but these conflict with your requirements or minimum-stability.
  Problem 2
    - Conclusion: don't install nesbot/carbon 2.17.1
    - Installation request for iidestiny/flysystem-oss ^1.3.3 -> satisfiable by iidestiny/flysystem-oss[1.3.3].
    - Installation request for laravel/framework (locked at v5.6.28, required as 5.6.*) -> satisfiable by laravel/framework[v5.6.28].


和carbon冲突了

**Comment by ycgambo** [comment]
更新了项目包，重新装了一下就好了。
如果没什么依赖的话，还是不要用高版本的carbon吧，我们这边还有一些项目用的laravel5.5

**Comment by iiDestiny** [comment]
一会发布新版本降低 Carbon 到 `laravel 5.5` 默认的 `^1.24.1`
