### ISSUE TITLE
OSS \ Core \ OssException : RequestId: 5CD3569DABF16F2EE7AF112B

### ISSUE THREAD

**Issue by xoxoj** [iiDestiny/laravel-filesystem-oss#8]
上传图片的时候，报这个错误

vendor/aliyuncs/oss-sdk-php/src/OSS/Result/Result.php
    public function parseResponse()
    {
        $this->isOk = $this->isResponseOk();
        if ($this->isOk) {
            $this->parsedData = $this->parseDataFromResponse();
        } else {
            $httpStatus = strval($this->rawResponse->status);
            $requestId = strval($this->getRequestId());
            $code = $this->retrieveErrorCode($this->rawResponse->body);
            $message = $this->retrieveErrorMessage($this->rawResponse->body);
            $body = $this->rawResponse->body;
 
            $details = array(
                'status' => $httpStatus,
                'request-id' => $requestId,
                'code' => $code,
                'message' => $message,
                'body' => $body
            );
            throw new OssException($details);
        }
    }

**Comment by iiDestiny** [comment]
看看需要的配置都正确吗？

**Comment by xoxoj** [comment]
需要的配置都应该配好了

```
OSS_ACCESS_KEY=xxxxxxxx
OSS_SECRET_KEY=xxxxx
OSS_ENDPOINT=https://images.mydomain.com
OSS_BUCKET=myoss
OSS_IS_CNAME=true
```

我们的oss设置了cdn，也自定义了域名。

所以是这样配置的

**Comment by iiDestiny** [comment]
https://help.aliyun.com/document_detail/32005.html  对照这里面的错误码看看

**Comment by xoxoj** [comment]
@iiDestiny 

错误是这样的：

`HttpCode:403	ErrorCode:SignatureDoesNotMatch	ErrorMsg:The request signature we calculated does not match the signature you provided. Check your key and signing method.
签名不匹配；`

如果我把OSS_ENDPOINT换成
`OSS_ENDPOINT=https://oss-cn-shanghai.aliyuncs.com`

`OSS_IS_CNAME = false`

就可以正常上传了，但问题是，我在oss后台绑定过自定义域名呀，还开启了cdn，所以说，我只能
`OSS_ENDPOINT = https://oss-cn-shanghai.aliyuncs.com`
这样来设置了吗？

**Comment by iiDestiny** [comment]
oss 后台手动绑定域名，就可以正常使用。

![image](https://user-images.githubusercontent.com/17637481/57425103-91c1f800-724c-11e9-94e7-da8728bf1485.png)

我这边测试是可以的。文档上面也是用的自定义域名来上传的。

**Comment by xoxoj** [comment]
@iiDestiny 帅哥，我在oss后台手动绑定域名了，并且是正常状态的。只不过是配了CDN，难道是CDN的问题？

我要发封邮件给你 :D:D
