### ISSUE TITLE
getUrl 方法获取的url不能配置强制https么？

### ISSUE THREAD

**Issue by justmd5** [iiDestiny/laravel-filesystem-oss#9]
如题，endpoint写https方式不行，因为 bucket 还有配置，配完后获得URL就不正确了

**Comment by iiDestiny** [comment]
不好意思最近有点忙，等会我看看什么问题。

**Comment by justmd5** [comment]
> 不好意思最近有点忙，等会我看看什么问题。

感谢

**Comment by fengerwoo** [comment]
两个问题
1，$disk->put 上传文件不能指定文件名
2，$disk->put 上传ipa文件，文件后缀成了zip
@justmd5

**Comment by justmd5** [comment]
@fengerwoo 你at我没用啊，at作者呗，😄

**Comment by iiDestiny** [comment]
@justmd5 

![image](https://user-images.githubusercontent.com/17637481/66893805-79d37900-f021-11e9-8939-712a67ef0af7.png)
![image](https://user-images.githubusercontent.com/17637481/66893810-7f30c380-f021-11e9-8d1a-7aa09ddc395d.png)

如果关于域名配置有什么不明白可以看看这个 [issue](https://github.com/iiDestiny/laravel-filesystem-oss/issues/11)

**Comment by iiDestiny** [comment]
@fengerwoo 我试是可以的。你看看 laravel 文档
